# Generated by Django 6.0.5 on 2026-05-31 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('easypaisa', 'EasyPaisa'), ('jazzcash', 'JazzCash'), ('bank', 'Bank Transfer')], max_length=15)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
        ),
    ]
