# Generated by Django 6.0.5 on 2026-06-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('easypaisa', 'EasyPaisa'), ('jazzcash', 'JazzCash')], max_length=15),
        ),
    ]
