# Generated by Django 6.0.5 on 2026-06-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='security_answer',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
