# Generated by Django 6.0.5 on 2026-06-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontent',
            name='content_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('routine', 'Routine')], max_length=10),
        ),
    ]
