# Generated by Django 6.0.5 on 2026-07-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_coursecontent_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontent',
            name='content_type',
            field=models.CharField(choices=[('Pdf', 'Pdf'), ('routine', 'Routine')], max_length=10),
        ),
    ]
