# Generated by Django 6.0.5 on 2026-09-23 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='membership_plan',
            field=models.CharField(choices=[('basic', 'Basic  PKR 2000'), ('standard', 'Standard  PKR 3500'), ('premium', 'Premium  PKR 5000')], default='basic', max_length=10),
        ),
    ]
