# Generated by Django 6.0.5 on 2026-09-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_membership_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
